# Generated by Django 3.0.3 on 2020-03-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
                ('tg_nick', models.CharField(max_length=128)),
            ],
        ),
    ]
