# Generated by Django 3.0.3 on 2020-03-12 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1024)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(32)])),
                ('is_busy', models.BooleanField(default=False)),
            ],
        ),
    ]
