# Generated by Django 3.0.3 on 2020-03-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='short_description',
            field=models.TextField(default='some short description', max_length=128),
        ),
    ]
