# Generated by Django 3.0.3 on 2020-03-06 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200304_1846'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
